#### create task
POST http://localhost:4000/api/tasks
Content-Type: application/json

{
    "title": "Task 1",
    "description": "Task 1 description",
    "userId": "68e69a8dff713cacf289ac92"
}

### test route
GET http://localhost:4000/

### get all tasks
GET http://localhost:4000/api/tasks

### register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username": "aanafi",
    "email": "ayost.com",
    "password": "ayoub",
    "role": "admin"
}

### login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "ayoub@test.com",
    "password": "ayoub"
}


### me
GET http://localhost:4000/api/auth/me
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTY5YThkZmY3MTNjYWNmMjg5YWM5MiIsImVtYWlsIjoibW91YWRAdGVzdC5jb20iLCJpYXQiOjE3NTk5NDM2MzN9.2090LQ89Ie2PkkKG-vua1HZBhIZ7GOF0hUXH1nZEtKw


## update task
PUT http://localhost:4000/api/tasks/68e7d74ef134be662c297fc0
Content-Type: application/json

{
    "title": "Updated Task",
    "description": "Updated description",
    "isCompleted": true,
    "status": "done"
}